
package com.vmrepository.repoguardwebserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddVMIImplementationService", targetNamespace = "http://RepoGuardWebServer.vmrepository.com/", wsdlLocation = "http://localhost:6070/?wsdl")
public class AddVMIImplementationService
    extends Service
{

    private final static URL ADDVMIIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDVMIIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName ADDVMIIMPLEMENTATIONSERVICE_QNAME = new QName("http://RepoGuardWebServer.vmrepository.com/", "AddVMIImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6070/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDVMIIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        ADDVMIIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public AddVMIImplementationService() {
        super(__getWsdlLocation(), ADDVMIIMPLEMENTATIONSERVICE_QNAME);
    }

    public AddVMIImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDVMIIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AddVMIImplementationService(URL wsdlLocation) {
        super(wsdlLocation, ADDVMIIMPLEMENTATIONSERVICE_QNAME);
    }

    public AddVMIImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDVMIIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public AddVMIImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddVMIImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AddVMIImplementation
     */
    @WebEndpoint(name = "AddVMIImplementationPort")
    public AddVMIImplementation getAddVMIImplementationPort() {
        return super.getPort(new QName("http://RepoGuardWebServer.vmrepository.com/", "AddVMIImplementationPort"), AddVMIImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddVMIImplementation
     */
    @WebEndpoint(name = "AddVMIImplementationPort")
    public AddVMIImplementation getAddVMIImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://RepoGuardWebServer.vmrepository.com/", "AddVMIImplementationPort"), AddVMIImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDVMIIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw ADDVMIIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return ADDVMIIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
